# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: VMC KAOS™ ~JOGJA~081227277298~
email: your-email@example.com
description: > # this means to ignore newlines until "baseurl:"
  Yet another Jekyll theme. It is designed for business purpose and ported by 
  Melvin Ch'ng.
baseurl: "https://vmckaos.github.io/jasakonveksi/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Company Information
company_name: VMC KAOS™ ~JOGJA
address_line: Via Ludovisi 39-45, Rome, 54267, Italy
telephone_number: 081227277298
fax_number: 
company_email:
google_map:https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1976.5064258484692!2d110.4095559!3d-7.788461377623258!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x2e7a59e3f5c96e8d%3A0x6f0d1bd72ced21e0!2sVMC%20KAOS%E2%84%A2%20~%200812%202727%207298%20~Konveksi%20Jogja%20yang%20memproduksi%20Kaos%2C%20jaket%20dan%20lainnya.%20Kami%20adalah%20vendor%20kaos%20jogja%20yang%20sudah%20berpengalaman%20memenuhi%20kebutuhan%20banyak%20konsumen.%20Dengan%20kualitas%20premium%20kami%20bisa%20menawarkan%20kaos%20dengan%20harga%20pabrik!5e0!3m2!1sid!2sid!4v1613888913301!5m2!1sid!2sid" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy">
# Social Link
facebook_link: http://www.facebook.com
twitter_link: http://www.twitter.com
linkedin_link: http://www.linkedin.com
googleplus_link: http://plus.google.com

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
